%%{init: {'theme':'default'}}%%
%%{css: '.mermaid { background-color: #fff !important; }'}%%
gantt
title Sprint 1
section Planificación
Tarea 1 :a1, 2025-10-26, 2d
Tarea 2 :a2, after a1, 3d
section Desarrollo
Tarea 3 :a3, after a2, 5d
